### PR TITLE
update a Readme

### PR DESCRIPTION
**Pull request by DHX98**

### CODE REVIEW

**Review by taylorez — APPROVED** [review]
Looks good to me

**Comment by DHX98** [comment]
merge

**Review by taylorez — APPROVED** [review]
looks good

**Comment by taylorez** [comment]
looks good

**Review by taylorez — APPROVED** [review]

**Comment by DHX98** [comment]
Updated

**Comment by taylorez** [comment]
#1 Looks good. Aproved

**Pull request merged**
